#!/usr/bin/env python3
"""Render the shared agent prompts into Codex custom-agent TOML files.

The prompt bodies in ``agents/*.md.tmpl`` are provider-neutral and stay the single
source of truth for both runtimes. Claude Code reads them directly (Markdown
with YAML frontmatter); Codex needs one standalone TOML file per agent under
``~/.codex/agents/``, so this script converts them instead of duplicating them.

Every generated file carries the three fields Codex requires — ``name``,
``description``, ``developer_instructions`` — plus the model, reasoning effort
and sandbox the role needs, taken from the Codex plan profile (``profiles/codex-pro.json`` or ``profiles/codex-plus.json``).

Why the model is always written out: a Codex custom-agent file that omits
``model`` inherits the resolved value — an explicit spawn value, then the
``[agents]`` default, then the parent's. For a STRONG or EXPERT role that means
an escalation could silently resolve back to the Terra default. Pinning the
model *in the file* is what makes the tier real, because a value set in the file
takes precedence over everything resolved before it.

The same reasoning produces the ``ai-risk-strong`` and ``ai-planner-strong``
variants: Codex has no per-call ``model`` override that survives a custom agent
file, so "re-run ai-risk on the STRONG tier" has to be a different agent.

  render-codex-agents.py --src <repo-root> --out <dir> [--profile <path>]
"""
import argparse
import json
import os
import re
import sys

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)


def die(message):
    print(f"render-codex-agents: {message}", file=sys.stderr)
    sys.exit(1)


def split_agent(path):
    """-> (frontmatter dict, body). Only the scalar keys we need are parsed;
    the frontmatter is a fixed, hand-written shape, not arbitrary YAML."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    match = FRONTMATTER.match(text)
    if not match:
        die(f"{path} has no YAML frontmatter")
    head, body = match.group(1), text[match.end():]
    fields = {}
    for line in head.splitlines():
        if line.startswith("#") or ":" not in line or line[:1].isspace():
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields, body.strip("\n")


def toml_basic(value):
    """A TOML basic string (one line)."""
    out = value.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "").replace("\t", "\\t")
    return f'"{out}"'


def toml_multiline(value):
    """A TOML multi-line string. Literal (''') by default so backslashes in the
    prompt survive verbatim; basic (\"\"\") with escaping if the body would
    close a literal string."""
    if "'''" not in value and not value.endswith("'"):
        return "'''\n" + value + "\n'''"
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if escaped.endswith('"'):
        escaped = escaped[:-1] + '\\"'
    return '"""\n' + escaped + '\n"""'


def render(name, spec, profile, src):
    tier = spec.get("tier")
    if tier not in profile["tiers"]:
        die(f"role {name} has unknown tier {tier!r}")
    model = profile["tiers"][tier]["model"]
    # A role may keep its own effort where it differs from its tier's (ai-discovery:
    # BALANCED model, low effort), so moving a role between tiers changes nothing.
    effort = spec.get("effort") or profile["tiers"][tier]["effort"]

    source = spec.get("source")
    if not source:
        parent = spec.get("variant_of")
        if not parent:
            die(f"role {name} declares neither `source` nor `variant_of`")
        parent_spec = profile["roles"].get(parent) or {}
        source = parent_spec.get("source")
        if not source:
            die(f"role {name} is a variant of {parent!r}, which has no `source`")

    fields, body = split_agent(os.path.join(src, "agents", source))
    description = spec.get("description_prefix") or fields.get("description", "")
    if spec.get("description_prefix") and fields.get("description"):
        description = f"{spec['description_prefix']} {fields['description']}"
    if not description:
        die(f"role {name} has no description")

    note = spec.get("escalation_note")
    if note:
        body = f"{note}\n\n{body}"

    if "{{" in body or "{{" in description:
        die(f"role {name} still has an unrendered placeholder")

    lines = [
        "# Generated by scripts/render-codex-agents.py from agents/%s." % source,
        "# Edit the shared prompt body there, not this file: an install overwrites it.",
        "name = %s" % toml_basic(name),
        "description = %s" % toml_basic(description),
        "model = %s" % toml_basic(model),
        "model_reasoning_effort = %s" % toml_basic(effort),
    ]
    if spec.get("sandbox_mode"):
        lines.append("sandbox_mode = %s" % toml_basic(spec["sandbox_mode"]))
    lines.append("developer_instructions = %s" % toml_multiline(body))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", required=True, help="repository root")
    parser.add_argument("--out", required=True, help="directory to write TOML into")
    parser.add_argument("--profile", help="defaults to <src>/profiles/codex-pro.json")
    args = parser.parse_args()

    profile_path = args.profile or os.path.join(args.src, "profiles", "codex-pro.json")
    try:
        with open(profile_path, encoding="utf-8") as fh:
            profile = json.load(fh)
    except (OSError, ValueError) as exc:
        die(f"cannot read {profile_path}: {exc}")

    os.makedirs(args.out, exist_ok=True)
    written = []
    for name, spec in profile["roles"].items():
        text = render(name, spec, profile, args.src)
        path = os.path.join(args.out, f"{name}.toml")
        tmp = f"{path}.tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
        written.append(name)

    # Parse every file back before claiming success: a prompt body that breaks
    # TOML quoting would otherwise only surface as a missing agent in Codex.
    try:
        import tomllib
    except ImportError:
        tomllib = None
    if tomllib is not None:
        for name in written:
            path = os.path.join(args.out, f"{name}.toml")
            try:
                with open(path, "rb") as fh:
                    data = tomllib.load(fh)
            except (OSError, ValueError) as exc:
                die(f"{path} is not valid TOML: {exc}")
            for required in ("name", "description", "developer_instructions"):
                if not data.get(required):
                    die(f"{path} is missing {required}")

    print("rendered %d Codex agents into %s" % (len(written), args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
